name: deploy-master-docker

on:
  push:
    branches: 
      - master
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: docker login
        run: |
          docker login -u ${{ secrets.name }} -p ${{ secrets.pass }} 
      - uses: actions/checkout@v1
      - name: deploy docker
        run: |
          echo $GITHUB_SHA
          rm -rf TarsDocker
          git clone https://github.com/TarsCloud/TarsDocker
          cd TarsDocker/framework
          ./build-master.sh
